# Generated by Django 6.0 on 2025-12-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_category_slug_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='color',
        ),
        migrations.AddField(
            model_name='productimage',
            name='color_code',
            field=models.CharField(blank=True, help_text='Hex color code like #000000', max_length=7),
        ),
        migrations.AddField(
            model_name='productimage',
            name='color_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
