# Generated by Django 6.0 on 2025-12-31 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='color_code',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='color_name',
        ),
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.color'),
        ),
    ]
