# Generated by Django 6.0 on 2026-01-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartjiapp', '0002_alter_category_image_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(upload_to='reviews/'),
        ),
    ]
