# Generated by Django 5.2.4 on 2026-01-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartjiapp', '0002_alter_product_is_featured_alter_product_stock_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock')], default='in_stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default='in_stock'),
            preserve_default=False,
        ),
    ]
