# Generated by Django 5.2.4 on 2026-01-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartjiapp', '0002_alter_product_is_featured_alter_product_stock_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
